# Site settings
title: I Do Declare
email: whyidodeclare@icloud.com
description: > # this means to ignore newlines until "baseurl:"
  Mostly ramblings with occasional lucidity, which though
  it may happen only once doesn't make me a liar.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://idodeclare.github.io" # the base hostname & protocol for your site
# twitter_username: 
github_username:  idodeclare

# Build settings
markdown: kramdown
